# Generated by Django 3.2.8 on 2021-10-08 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
