# Generated by Django 3.2.8 on 2021-10-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
